### ISSUE TITLE
Polyfill Suggestion

### ISSUE THREAD

**Issue by TiKevin83** [ApoorvSaxena/lozad.js#104]
Hi,
I found a small bit of JS and reworked it to only load the w3c polyfill if the browser doesn't yet support the IntersectionObserver API, you might want to use it in your FAQ.  If there's a more efficient way of doing this so that you get the native IntersectionObserver behavior on Chrome/Firefox/Edge and the polyfill on Safari/IE do let me know.

if (!('IntersectionObserver' in window)) {
    var js = document.createElement("script");
    js.src = "https://raw.githubusercontent.com/w3c/IntersectionObserver/master/polyfill/intersection-observer.js";
    document.getElementsByTagName('head')[0].appendChild(js);
}

**Comment by ApoorvSaxena** [comment]
@TiKevin83 thanks for sharing this, have updated [FAQs](https://github.com/ApoorvSaxena/lozad.js/wiki/Frequently-Asked-Questions)
