### ISSUE TITLE
Lazy loading the low quality version

### ISSUE THREAD

**Issue by marcospgp** [ApoorvSaxena/lozad.js#105]
* On a project I'm working on, we're using Lighthouse for performance testing, which is pretty much mobile 3G first. This means that every http request counts!

* We are using the LQIP technique: `<img>` tags have a low quality thumbnail as `src`, and the full resolution image as `data-src`, which is lazy loaded by javascript. I'm assuming this is possible with lozad as well.

* Right now we stand to gain over 2.5 seconds in load time if we were to reduce the number of HTTP requests for the thumbnails on page load.

* I was wondering if there is any interest for adding a lazy-lazyload feature to lozad, where instead of having a `src` that loads instantly and a `data-src` that is lazyloaded, we have `data-lq-src` or similar and `data-src`, which are both lazyloaded at the same time when they approach the viewport.

Is this idea stupid and/or a little crazy? I think it might sound stupid to load two images at the same time, but when you think about being mobile and 3G first, the time saved in load-time HTTP requests for long pages is valuable, and loading the two images at the same time is ok because in a slow connection the thumbnail should load noticeably faster, making it is still worth having.

Thank you for your time!!

**Comment by TiKevin83** [comment]
It sounds like you might want to convert your micro-thumbnails to data URLs, that would let you inline the image and reduce your HTTP requests and then just use lozad for the final lazy load step.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs
