### ISSUE TITLE
Lozad and Choo?

### ISSUE THREAD

**Issue by istvanvasil** [ApoorvSaxena/lozad.js#106]
Hi!

I am trying to implement Lozad into a website that I am building using a framework called[ Choo](https://choo.io/). I am a full-time designer and do coding on the side. So my knowledge is limited and would appreciate some help with this.

Anyone has any experience pairing the above two?

I have an `images.js` file that returns images by mapping an array of file names and returning the html code for each image with srcset. Super straightforward but I couldn't make it work with Lozad. It doesn't load the image and the page shows a broken image link. 

`return html ` 
`<div>`
`<img src="image.jpg" srcset="lowres.jpg, mediumres.jpg, highres.jpg...etc.">`
`</div>...`

The whole code then it's bundled up using browserify. 

I know this is quiet broad and vague but any help is appreciated. 

Thank you!

**Comment by ApoorvSaxena** [comment]
@istvanvasil possible to share a codepen implementation for the same for us to help you out?

**Comment by istvanvasil** [comment]
I went ahead and figured out a workaround actually. But thank you for you help.
