### ISSUE TITLE
Lazy loading background image on <body> tag

### ISSUE THREAD

**Issue by rafaaro** [ApoorvSaxena/lozad.js#109]
I got a doubt about how to properly lazy load background images on `<body>` tag.

For reference, I'm using [TailwindCSS](https://tailwindcss.com/docs/what-is-tailwind/) framework.

I added the `lozad` class to the `<body>` tag and set a background image with gradient overlay by defining a `background-image` in my stylesheet like this:

```
body {
  background-image: linear-gradient(to top left, config('colors.gd-primary'), config('colors.gd-secondary')), url('../images/background.jpg');

  @apply .bg-fixed .relative .bg-secondary .bg-cover .bg-center .bg-no-repeat ;
}
```
The image loads and everything seems fine, however I'm still unsure if the image is lazy loaded and if this is the proper way to work this around. Also read about the `data-background-image` example on project's README.md so it also makes me wonder if my approach is right.

Is there a better way to do this or is it even working at all?

**Comment by ApoorvSaxena** [comment]
@rafaaro possible to share a codepen implementation?
