### ISSUE TITLE
Check if print?

### ISSUE THREAD

**Issue by hubpork** [ApoorvSaxena/lozad.js#111]
Hello
Thanks for this great plugin. I use it productively and I am enthusiastic. I know that hardly any pages are printed today. But the customer wants a page that can be printed. Is there a hint?

**Comment by ApoorvSaxena** [comment]
@hubpork you can load all images before triggering print by making use of [triggerLoad API](https://github.com/ApoorvSaxena/lozad.js/blob/master/src/lozad.js#L90) documented [here](https://github.com/ApoorvSaxena/lozad.js#usage)
