### ISSUE TITLE
SEO friendly?

### ISSUE THREAD

**Issue by sajadghawami** [ApoorvSaxena/lozad.js#113]
Hey there,

does anyone have any experience with this library and its SEO-friendliness? If so, would be glad if you could share your experiences!

Thanks.

**Comment by ApoorvSaxena** [comment]
@sajadghawami had answered this question in [FAQs section](https://github.com/ApoorvSaxena/lozad.js/wiki/Frequently-Asked-Questions#does-lazy-loading-of-image-impacts-seo)
