### ISSUE TITLE
If I use picturefill for IE11 would this plugin work?

### ISSUE THREAD

**Issue by code-mattclaffey** [ApoorvSaxena/lozad.js#114]
Hey,

Just checking if this would work if my browser had the picturefill polyfill for IE11?

**Comment by ApoorvSaxena** [comment]
Lozad was [tested](https://github.com/ApoorvSaxena/lozad.js/pull/54#issue-145493205) by one of the community member on IE9 and it worked perfectly, thus should work fine in IE11 as well
