### ISSUE TITLE
Use Lozad to know when element has entered viewport

### ISSUE THREAD

**Issue by martinbroos** [ApoorvSaxena/lozad.js#118]
Hi, 

Is it possible to use lozad to know when an element has entered the viewport?

When doing this:
`<div class="lozad"></div>`

It results in this

`<div class="lozad" data-loaded=true></div>`

So Lozad seems perfect to do this type of checking, but I don't now if there is a way to listen for this event in javascript? This would save me an extra library such as Waypoint.js

If this is not in the scope of the project, I understand. Thanks for this great library.

**Comment by martinbroos** [comment]
It was actually quite easy to use the IntersectionObserver Api myself. For anyone wanting to do the same thing check out https://alligator.io/js/intersection-observer/

So if you don't see the need to add events to Lozad the above sollution is also fine with me.

**Comment by ApoorvSaxena** [comment]
@martinbroos as you mentioned, this requirement deviates from the core purpose of lozad
