### ISSUE TITLE
Bootstrap carousel

### ISSUE THREAD

**Issue by kickbk** [ApoorvSaxena/lozad.js#123]
First slide on BS4 carousel gets lazy loaded just fine. Other images not. (You can inspect elements and see that the first image is data-loaded="true", other images not)
See https://codepen.io/kickbk/pen/qyLOeN

How do we apply lazy loading to images in slides when they enter into view?

**Comment by TiKevin83** [comment]
You're only selecting the first img with querySelector in your JS, you should be all set just changing that to querySelectorAll as in the example.
