### ISSUE TITLE
Should getElements() be scoped to the root option?

### ISSUE THREAD

**Issue by i-like-robots** [ApoorvSaxena/lozad.js#125]
The `root` option added in #122 allows the configuration of a specific element to use as the "viewport". Observable elements [must be children of the root][0] but the `getElements()` function still fetches elements [scoped to the document][1]. Should it be scoped to the root too?

It is currently possible to disambiguate this by providing a more specific selector but it may not always be possible to uniquely identify elements:

```js
lozad('#root-el .lozad') { root: document.getElementById('root-el') })
```

[0]: https://www.w3.org/TR/intersection-observer/#intersection-observer-interface
[1]: https://github.com/ApoorvSaxena/lozad.js/blob/c32f60f3e0e5c5cfbf91290a4e489cba2e51d57b/src/lozad.js#L65

**Comment by ApoorvSaxena** [comment]
@i-like-robots what do you suggest to overcome this issue?

**Comment by ApoorvSaxena** [comment]
thanks for your contribution @i-like-robots 👍
