### ISSUE TITLE
Lozad working with Masonry Grid

### ISSUE THREAD

**Issue by ZCweb** [ApoorvSaxena/lozad.js#126]
Check out my codepen. https://codepen.io/zcweb/pen/KBjYqW

I am having an issue in our wordpress theme getting lazyload to work with masonry grid. It would be great to have lazyload work down the page. We are lazyloading background images so you'll see it on the 'section' tag. I also lazyload image in the outputted wordpress content which is not in this example. In our theme loaded from Advanced Custom Fields. So I need this to not only lazyload the masonry grid but also other elements labeled lozad throughout the theme. I've gotten lazyload to work except for masonry.

I saw this pen https://codepen.io/aminta/pen/VdeyVr but what that guy did doesn't apply to what I'm doing.

I would greatly appreciate some help with this.

**Comment by TiKevin83** [comment]
Currently your masonry grid code is depending on images being loaded before it runs to see their size and know how to flow the layout.  You'll need to hard style the sizes of the boxes that the images will fit in and then load the images after the masonry grid has flowed the layout based on those box sizes.  You'll want to use data-src instead of src on the image tags as well, right now lozad isn't working at all in your pen because the images have proper src tags.

**Comment by ZCweb** [comment]
I made it data-src instead of src so that is working now.

So my images load in a div called 'box'. So I put styles in like: <div class="box" style="width:1080px; height:520px;"> for an image that is 1080px by 520px. I did a couple but it looks like it is loading the image to be huge across the page and masonry isn't putting it into the 3 columns which I have masonry set at. 33%

**Comment by TiKevin83** [comment]
Try doing style="width:360px; height:240px; width="360" height="240" on the image tag only instead of the box with the appropriate height for each image instead of 240

**Comment by ZCweb** [comment]
OK thanks. I did it: https://codepen.io/zcweb/pen/KBjYqW but the images are looking stretched out constrained by width and respecting the height. There is a max width of 100% which is probably constraining the width. 

I then changed the height to be the actual width and height:auto; which looked right but then when going to the 4th image and so on it ended up looking funky like before. So what I have going on now is the height and width of actual dimensions on the image and no style="" on the box container. Could you experiment with a couple scenarios in the pen. it is 3 column

I have 4 images here and it is looking better minus the stretching. note my CSS is saying .box is 33% and images are max-width:100% with height of auto (overriden by inline style).

I think this should be easier to play around with no that the actual heights and widths are declared.

**Comment by TiKevin83** [comment]
https://codepen.io/tikevin83/pen/mGyOMZ

I looked up some tricks to create boxes with set aspect ratios and came up with this.  All you do is add a hard coded padding-bottom style to each box with the percent being 33% (the width of the box) multiplied by the photo's native aspect ratio.

**Comment by ZCweb** [comment]
Cool that worked!

I have an issue when resizing the screen which adds incorrect padding - too much padding. The width stays at about 33% but the bottom padding is much larger than the image. Something gets screwed up when dragging the screen. If I refresh the page at the new screen size then the layout looks good. It is just moving the window after the initial page load as it calculates how to fit everything together where things get screwed up.

At that point it is more of a masonry grid option. But if you can think of a lozad callback to fix this feel free to offer help.

**Comment by TiKevin83** [comment]
I think a true fix would require improving the masonry script itself so that it handles allocating appropriately sized spaces for the images, instead of trying to retrofit the appropriate space with padding.
