### ISSUE TITLE
Image loaded

### ISSUE THREAD

**Issue by SylvainAllignol** [ApoorvSaxena/lozad.js#128]
Hello,
The data-loaded is triggered before the ims src is actually replaced, so a CSS transition between the 2 states is not possible

**Comment by TiKevin83** [comment]
Hi Sylvian,
I use the data-loaded trigger for CSS transitions in this example slideshow project.  I just wrapped the images in a container div and transitioned the container instead of the image itself.
https://codepen.io/tikevin83/pen/BPvQMz
