### ISSUE TITLE
Amend readme to show use of <noscript> fallback

### ISSUE THREAD

**Issue by brucelawson** [ApoorvSaxena/lozad.js#13]
As per previous issue.

**Comment by ApoorvSaxena** [comment]
This need not be mentioned in the README, as this implementation is not specific to library.
Reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/noscript

**Comment by brucelawson** [comment]
But the readme should show developers how to use lozad while still offering a fallback if there's no JS. It's responsible coding.

**Comment by styfle** [comment]
I agree it should be in the README.

Most people will likely migrate from simple `<img src="foo.png />` to lozad in which case, best practices should be demonstrated in the README.

**Comment by ApoorvSaxena** [comment]
information regarding this is now available in [FAQs](https://github.com/ApoorvSaxena/lozad.js/wiki/Frequently-Asked-Questions)
