### ISSUE TITLE
Improve compatibility of data-srcset with IE9-11 and other older browsers

### ISSUE THREAD

**Issue by gchtr** [ApoorvSaxena/lozad.js#142]
## Expected Behavior

When using `data-srcset` on an image tag, the `srcset` attribute should be set in IE9-11.

## Current Behavior

The `srcset` attribute is not set in IE9-11 with the following lines:

https://github.com/ApoorvSaxena/lozad.js/blob/6ec2448d7995218999676de0bddb28f26b1073ca/src/lozad.js#L25-L27

The reason is that direct manipulation of an attribute is only possible for supported attributes. The `srcset` attribute is not supported in older browsers, including IE11 (see the [compatibility table on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#Browser_compatibility)). That’s why the attribute won’t be set in the DOM and no image will show.

## Possible Solution

A possible solution would be to use `setAttribute`: 

```js
element.setAttribute('srcset', element.getAttribute('data-srcset'));
```

To check whether the direct manipulation of the attribute is supported by the browser, a check can be used:

```js
if (typeof element.srcset !== 'undefined') {
  element.srcset = element.getAttribute('data-srcset')  
} else {
  element.setAttribute('srcset', element.getAttribute('data-srcset'));
}
```

When using `setAttribute()`, an attribute will always be interpreted as a string, but since `srcset` should be interpreted as a string, the shorter version should be enough, I guess.

## Context

Picturefill is included to make responsive images work in older browsers.

## Steps to Reproduce (for bugs)

1. Add a `data-srcset` attribute to an image with class `.lozad` (<https://codepen.io/mindkomm/pen/PxZYwp>)
2. Open site (<https://s.codepen.io/mindkomm/debug/PxZYwp/yPMJjXNqGjRM>) in IE9, IE10 or IE11 and confirm that `srcset` attribute is not set.

## Tested on:

I tested it using `element.setAttribute()` on IE9, IE10 and IE11 in combination with Picturefill and it all worked.

**Comment by ApoorvSaxena** [comment]
@gchtr considering browser compatibility concerns, we can make use of `setAttribute` function everywhere instead of direct manipulation of element attribute, a PR contribution from you will be really helpful

**Comment by gchtr** [comment]
I just added the pull request.

> Considering browser compatibility concerns, we can make use of setAttribute function everywhere instead of direct manipulation of element attribute.

I think other attributes like `src`, `alt` and `style` are very well supported (HTML4) and wouldn’t need a special treatment. Maybe we don’t have to overoptimize 😉?

**Comment by ApoorvSaxena** [comment]
@gchtr thanks for your contributions, not overdoing makes perfect sense 😃
