### ISSUE TITLE
img alt tag displayed when js not available

### ISSUE THREAD

**Issue by ohlr** [ApoorvSaxena/lozad.js#146]
Hi,

given this implementation:

```
<img class="lozad" data-src="image.jpg" data-index="1" alt="myimage">
<noscript><img src="image.jpg" alt="myimage"></noscript>
```

when the visitor has js disabled, I see the alt element from the lozad image appearing above the noscript image. Is there any way to avoid this?

**Comment by Jab2870** [comment]
You could add the alt attribute with js? If you change `alt="myimage"` to `data-alt="my-image"` you could add the following when you start lozad:

```js
lozad('.lozad', {
    loaded: function(el) {
        if( el.dataset.alt ){
            el.alt = el.dataset.alt;
        }
    }
});
```

**Comment by ohlr** [comment]
Thanks!

**Comment by ohlr** [comment]
Remark: Although the answer from @Jab2870 does the job, I think from a SEO perspective it's not optimal. At least Lighthouse complains about missing alt tags.
I believe a solution like this [lazysizes](https://github.com/aFarkas/lazysizes#the-noscript-pattern) is better from SEO perspective
