### ISSUE TITLE
 Won't duplicate dom generated by duplicate data be observed

### ISSUE THREAD

**Issue by huan0118** [ApoorvSaxena/lozad.js#148]
I used scroll event ajax to load the same batch of data into the page, and the page also loads the same batch of data, but after observing the first batch of data, the subsequent data will not be observed and the data-src attribute has not been replaced with the actual SRC

**Comment by ApoorvSaxena** [comment]
@huan0118 possible to share a Codepen implementation of the issue?

**Comment by huan0118** [comment]
Sorry, I think it's caused by other plug-ins.
