### ISSUE TITLE
data-srcset - responsive image doesn't work

### ISSUE THREAD

**Issue by virginiarcruz** [ApoorvSaxena/lozad.js#151]
I need to change the images per each breakpoint.
For example, for
max-width: 767px: image-mobile.jpg
max-width: 1024px: image-desktop.jpg

I'm trying this way, but doesn't work for me:

```
<div class="image-wrapper">
  <img class="lozad"
  data-src="https://picsum.photos/1600/900?image=3"
  data-srcset="https://picsum.photos/767/800?image=3 767w,
  https://picsum.photos/1024/900?image=3 1024w">
</div>
```
Should I, add another config to work?

**Comment by TokyoWeb** [comment]
I had the same issue understanding or making work the data-srcset. 

See my issue https://github.com/ApoorvSaxena/lozad.js/issues/134 then code working fine.
