### ISSUE TITLE
Lozad for Google Maps?

### ISSUE THREAD

**Issue by BeholdPL** [ApoorvSaxena/lozad.js#153]
Hi!

Is there any possibility to use lozad with Google Maps? Im looking a lazy load solution for ACF Google Maps and WP Google Maps Pro plugin on Wordpress.

**Comment by ApoorvSaxena** [comment]
@BeholdPL I haven't explored working of any of the plugins before that you've mentioned, thus can't say much. Check with their authors about how their plugins can be lazy loaded.
