### ISSUE TITLE
Not working in Safari on Mac

### ISSUE THREAD

**Issue by milianriedel** [ApoorvSaxena/lozad.js#16]
In last Safari (10.1.2) images dont load. Error in console: "Can't find variable: IntersectionObserver".

**Comment by ApoorvSaxena** [comment]
Fixed. Will update the demo to load IntersectionObserver polyfill if browser's support is not available.

**Comment by milianriedel** [comment]
Awesome. You're great 👍

**Comment by ApoorvSaxena** [comment]
[Demo](https://apoorv.pro/lozad.js/demo/) now makes use of IntersectionObserver polyfill. @milianriedel thanks for opening up the issue.

**Comment by daizch** [comment]
@ApoorvSaxena Your demo is till not working in Safari(12.0) on Mac.

**Comment by ApoorvSaxena** [comment]
![screenshot 2018-11-25 at 1 38 39 pm](https://user-images.githubusercontent.com/307583/49002348-58f20300-f185-11e8-92bf-5a7216a14955.png)


I tested in Safari Version 12.0 (14606.1.36.1.9) and it's working perfectly fine for me. Please share more details about the exact error in a new issue, as it may be unrelated to this issue.
