### ISSUE TITLE
data-background-image not loading?

### ISSUE THREAD

**Issue by andrewcourtney** [ApoorvSaxena/lozad.js#177]
Hi there,

## Expected Behavior
I'm having problems getting a use-case of the data-background-image to work successfully. I've got an inline image to load and fade in when it appears within the viewport but the data-background-image is loading but then not appearing? I would like the background-image to lazy load and fade-in once it is  within the viewport.

## Current Behavior
I have applied the same class of "lozad" to all elements including the div element which has data-background-image applied top it. The attribute "data-loaded=true" appears correctly but the following does not happen:

1. Background image is not applied
2. Class of "fade" not applied to div
3. Opacity does not change as a result

Even when I force the opacity via DevTools the background-image is not applied.

## Steps to Reproduce (for bugs)
Please refer to the following example:
https://codepen.io/Shoxt3r/pen/pXZBoa

## Tested on:
Google Chrome Version 75.0.3770.100

Please let me know if any further information would be helpful to look into this.

Thanks!

**Comment by citricacid-pl** [comment]
I had similar issue and while debugging JS I found out that the image string is coming with line feed character at the end resulting in no setting the background. I have my image path generated with blade template so I have provided a `trim` directive to have the proper result.

Summarizing: trimming image path for background did the trick.

**Comment by LibbyJane** [comment]
> I had similar issue and while debugging JS I found out that the image string is coming with line feed character at the end resulting in no setting the background. I have my image path generated with blade template so I have provided a `trim` directive to have the proper result.
> 
> Summarizing: trimming image path for background did the trick.

You are a SAINT! I was tearing my hair out with this issue, thank you for posting ⭐
