### ISSUE TITLE
Lozad with varied-size images in multiple columns (masonry) 

### ISSUE THREAD

**Issue by cooperlovano** [ApoorvSaxena/lozad.js#178]
I am trying to use Lozad for a very image-heavy art portfolio - https://www.cooperlovano.design/new-bianca/ -  where the client wants a masonry grid (2-3 columns depending on browser size). The when the images load they push each other down and the formatting shifts until all the images in the constraining divs are loaded, and I gather that the solution is to hard code the placeholder sizes before the images are lazy loaded. But how do I do this when each thumbnail is a variable size, corresponding to the aspect ratio of the image?

Is there a way of implementing lozad to work on grids of images like this, in which columns are made based on varying image sizes? In a way where the whole grid does not shift when each images is lazy loaded? 

Thank you for your time, love this script

**Comment by UisgeBeatha436** [comment]
What about using flexbox? Tried to load the on my mobile, but that was a no-go. Too heavy to load.

**Comment by cooperlovano** [comment]
@UisgeBeatha436 thanks for your response~

I haven't looked too far into flex because having the masonry effect to work vertically (with variable heights) seemed like it would get tricky..  To avoid this behavior:  

![Screen Shot 2019-07-07 at 5 36 25 PM](https://user-images.githubusercontent.com/29786910/60774144-ed3e2400-a0dd-11e9-8c41-0afd5d726be7.png)

I'd have to set a hard coded container height and use `flex-flow: column wrap;` plus recalculate the container heights for various window widths. If that's the only solution that's ok, if I can find something that would work the currently implemented column-wrap property that would be better.

And damn haven't had that problem on my phone, I don't think flex would help that because on mobile they are already loading in one column (so lozad should be working fine and without this column wrapping issue)

**Comment by UisgeBeatha436** [comment]
Hi, 
Have a look at my gallery, based on Mansory lay-out. Framework is MDBootstrap Jquery. Hope this helps. 
https://www.uisge-beatha.eu/fotos-en-videos-rondom-uisge-beatha/fotoalbums
