### ISSUE TITLE
Remove dist folder from git

### ISSUE THREAD

**Issue by thiamsantos** [ApoorvSaxena/lozad.js#18]
Remove dist folder from to git as it is a file automatically generated and we don't need to keep track of them. In that way would be possible to keep the pull requests more clean. To accomplish this just add the [dist folder](https://github.com/reactjs/redux/blob/master/.gitignore#L4) [to the `gitignore` file](https://github.com/developit/preact/blob/master/.gitignore#L4) and add a [files property](https://docs.npmjs.com/files/package.json#files) to the `package.json` specifying the files to be included in the package when download it from npm. Right now [all the repo is included](https://unpkg.com/lozad@1.0.1/).

The oinly problem that I can see on doing this is that the demo uses a [relative path](https://github.com/ApoorvSaxena/lozad.js/blob/master/demo/index.html#L124) to the dist folder. But the demo can pull the project from a cdn (related #17).

**Comment by ApoorvSaxena** [comment]
> Remove dist folder from to git as it is a file automatically generated and we don't need to keep track of them.

Removing dist will require folks to implement the build procedure that we've implemented in our project, will seem overkill to new starters, though we can integrate [Travis CI](https://travis-ci.org/) to build `dist/` folder for us.

> add a files property to the package.json specifying the files to be included in the package when download it from npm. Right now all the repo is included.

This should be done, right away.

> But the demo can pull the project from a cdn

CDN itself refers to the dist folder minified file.

**Comment by thiamsantos** [comment]
> Removing dist will require folks to implement the build procedure that we've implemented in our project.

Actually instead of download the files from github a newbie would download the files from the cdn in the same way. No need to to any build procedure.

https://cdn.jsdelivr.net/npm/lozad/dist/lozad.js
https://cdn.jsdelivr.net/npm/lozad/dist/lozad.min.js

> though we can integrate Travis CI to build dist/ folder for us.

The best way to do it is add a [`prepublish` script to `package.json`](https://docs.npmjs.com/misc/scripts) that run the build script. So even the `dist` being ignored by git, npm include it at the package.
