### ISSUE TITLE
Browser field should not point to minified build

### ISSUE THREAD

**Issue by antony** [ApoorvSaxena/lozad.js#180]
## Expected Behavior
Lozad's browser field in `package.json` should point to the ES build, as this field is used for bundlers which will then do their own transpilation, tree-shaking, and minification. Pointing at the minified/transpiled build causes this not to happen and results in larger bundle sizes and inability to debug.

## Current Behavior
Currently `browser` points at the minified build.

## Possible Solution
Point `browser` at the `.es` build, since anybody who wants a pre-minified version would be using `unpkg` or similar, and not relying on `package.json`.

## Steps to Reproduce (for bugs)
`npm i --save-dev lozad`

## Context
I cannot debug lozad in my build, I cannot control browser support, and my bundle size is negatively affected.

## Tested on:
* Browser Name and version: Chrome, Firefox
* Operating System and version (desktop or mobile): Desktop

**Comment by visibleajay** [comment]
Any hints on testing the working of this code.
```
  "browser": "dist/lozad.es.js",
  "main": "dist/lozad.js",
  "module": "dist/lozad.es.js",
```

**Comment by Alphasaurs** [comment]
#253
