### ISSUE TITLE
Issue with Lozad for Lazy Loading images on new Chrome 75

### ISSUE THREAD

**Issue by alaahariri** [ApoorvSaxena/lozad.js#181]
I have been facing an issue since upgraded to Chrome V75. The bug should be related to the Intersection Observer. I have reported this to Google since the very first day of the new Chrome release. My particular case is as the following:

1- I am using Lozad library for lazy loading images. This library utilizes intersection observer api.
2- I have my website in two languages. The English version is all ok. All images are loading as should be.
3- For the other language, no images are loading. The src attribute is not being replaced by data-src attribute as it should work. Instead, all images are using the static placeholder that I am using as src.
4- By the time I trigger any Ajax call on the affected pages, all images are loaded instantly.
5- I can confirm that the issue is specific to Chrome V 75 as I have rolled back to an earlier version and found no issues.

**Comment by citricacid-pl** [comment]
Unfortunately this issue is also appearing in Chrome 76 on Mac

**Comment by andredalmolin** [comment]
Here too, not working on Chrome :(...

**Comment by pascalschoeni** [comment]
chrome 77 as well

**Comment by JorgeSivil** [comment]
Did you try removing the threshold (if you have a custom one)? I have a problem with certain images in a list (all images are equal type / properties), and some are failing. I discovered that if I set threshold to 0 (default), they all work.
