### ISSUE TITLE
Should I use W3C polyfill for IntersectionObserver API?

### ISSUE THREAD

**Issue by minaminfo** [ApoorvSaxena/lozad.js#184]
Hi Saxena!
What's your views about using polyfill for IntersectionObserver API? Sure IntersectionObserver is not supported by old browsers. I found W3C polyfill but I'm afraid if it'll work with lozad as expected.
Need your suggestions!
Will this work fine with lozad or some special tweaking required?

**Comment by Strongground** [comment]
@minaminfo There is a polyfill that W3C recommends using. It is this one: https://polyfill.io/v3/polyfill.min.js?features=IntersectionObserver
It is also mentioned here by @ApoorvSaxena to be used. 

There isn't a "special polyfill" just for this single lazy loading library. Polyfills just modify the prototype of the object they are supporting, just implement the polyfill and lazyloading and you will be fine.

Cheers!
