### ISSUE TITLE
Feature Request: Multiple Background Images

### ISSUE THREAD

**Issue by fatihbatal** [ApoorvSaxena/lozad.js#190]
With a small change, Lozad would support multiple background images as
```html
<div style="background: url( 'path/to/main/image' ), url( 'path/to/fallback/image' );"></div>
```

Here's my suggestion:
```js
if (element.getAttribute('data-background-image')) {  
  element.style.backgroundImage = "url('" + element.getAttribute('data-background-image').split( ',' ).join( "'),url('" ) + "')";  
}
```
on line 54 of main file (lozad.js) instead of
```js
if (element.getAttribute('data-background-image')) {  
  element.style.backgroundImage = 'url(\'' + element.getAttribute('data-background-image') + '\')';  
}
```

Then the initialization would be as:
```html
<div class="lozad" data-background-image:"path/to/main/image,path/to/fallback/image"></div>
```

Needless to say, this change is also backward compatible.

What do you think?

**Comment by ApoorvSaxena** [comment]
@fatihbatal I'll be glad if you can open a PR for your change, code looks fine.

**Comment by fatihbatal** [comment]
I opened a pull request just now.
This is the very first action of me on GitHub, btw.
So, I had to follow some tutorials and StackOverflow threads to keep up.
Hopefully, I didn't do anything wrong (fingers crossed).

**Comment by ApoorvSaxena** [comment]
thanks for your contributions @fatihbatal 💯
