### ISSUE TITLE
Not working in IE 11

### ISSUE THREAD

**Issue by webdevhobby** [ApoorvSaxena/lozad.js#204]
Our sites images using lozad don't load in IE 11. I think it works before but not anymore. I checked the demo site, https://apoorv.pro/lozad.js/demo/ and confirmed that it is really not working now.

**Comment by gardavis** [comment]
Error in JavaScript console: Object doesn't support property or method 'assign'

e = Object.assign({}, c, t)

**Comment by razi-ed** [comment]
can i please work on this?

**Comment by ApoorvSaxena** [comment]
fixed by https://github.com/ApoorvSaxena/lozad.js/pull/207, README and Demo page has been updated

**Comment by ApoorvSaxena** [comment]
@webdevhobby @gardavis can you please help in verifying the same in IE browser?

**Comment by gardavis** [comment]
Adding the polyfills for Object.assign and IntersectionObserver do get Lozad to work fine in IE11.


  *   The Object.assign polyfill fixes the Javascript error about the assign() function undefined.


  *   The IntersectionObserver polyfill allows images to display and the observer “load” function to be called during page scrolling.

Thanks,
Gary Davis

**Comment by benjamingries** [comment]
What is the best way to handle this via webpack and ES6 syntax? Corejs didn't transform the object assign statement in my javascripts ...

**Comment by hn1** [comment]
"Adding the polyfills for Object.assign and IntersectionObserver do get Lozad to work fine in IE11."
Unfortunately it does not. Its all over the place - No Polyfill will make this work!
Any ideas. It used to work perfectly upt o version 1.7 - What happened!
Sometimes progress is no good!

**Comment by benjamingries** [comment]
I need some time to get this, but these polyfills doesn't polyfill the append function ( it's documentated here: #221 )
