### ISSUE TITLE
The latest relase 1.14.0 breaks JS load in IE11

### ISSUE THREAD

**Issue by eNkru** [ApoorvSaxena/lozad.js#213]
we are using the jsdelivr CDN link and the latest 1.14.0 release break our JS load on IE 11.

The error message 

> object doesn't support property or method 'assign'

All or JS followed by Lozad is not loaded and end up with a broken website.

After we switch back to 1.9.0, all loaded.

**Comment by ApoorvSaxena** [comment]
This information has been provided here #204
