### ISSUE TITLE
Is it better to add observer.disconnect() ?

### ISSUE THREAD

**Issue by yxwu** [ApoorvSaxena/lozad.js#214]
As stated in https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver/disconnect, seems it could be better to do observer.disconnect().

So is it ok to add this feature to lozad.js, such as 
```
export default function (selector = '.lozad', options = {}) {
  ...
  return {
    observe() {...},
    triggerLoad() {...},

    cleanup() {
        observer && observer.disconnect && observer.disconnect();
    }
  }
```
Thanks

**Comment by ApoorvSaxena** [comment]
@yxwu a better implementation will be to return the intersectionObserver instance, so that any such new function will be available to use instead of whitelisting it up in the library, one after the other.

**Comment by yxwu** [comment]
I noticed the observer instance is already there in the returned obj.
You can close this issue, Thanks.
