### ISSUE TITLE
Q: is lozad using .observe() obsolete feature?

### ISSUE THREAD

**Issue by gacallea** [ApoorvSaxena/lozad.js#224]
Hi, I've looked at the source and could not find .observe() defined. I may have missed it tho.

However I would ask: is lozad using this? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/observe or just a same name internal function?

Please and thank you

**Comment by damac23** [comment]
As stated in den README it uses the IntersectionObserver(): https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API
