### ISSUE TITLE
Donating lozad.com

### ISSUE THREAD

**Issue by ad31mar** [ApoorvSaxena/lozad.js#229]
Heya Apoorv, tried reaching you via email.

I'm a huge fan of lozad.js and have been using it on [Binned Art](https://binnedart.com) in it's full glory!

I have another side project called [Zlipa](https://zlipa.com) which does short dotcoms for makers and bootstrappers, and a couple of days ago `lozad.com` expired and I snatched it. 

I would like to donate it to the lozad.js project 🙂

**Comment by ApoorvSaxena** [comment]
@ad31mar thanks for this, Lozad started off as side project (still is) and at present is hosted at https://apoorv.pro/ which seems fine. Thanks again, appreciate the great gesture 👍
