### ISSUE TITLE
Data-poster not available when installing from npm

### ISSUE THREAD

**Issue by lonepalmus** [ApoorvSaxena/lozad.js#230]
## Expected Behavior
To lazyload the poster for a video with data-poster, like in the demo https://apoorv.pro/lozad.js/demo/

## Current Behavior
After installing from npm (v1.14.0) the data-poster is not swapped for poster. 

## Possible Solution
Publish the latest changes to npm?

## Tested on:
* Chrome Version 80.0.3987.132
* MacOS Mojave 10.14.6

**Comment by ApoorvSaxena** [comment]
Available https://www.npmjs.com/package/lozad#example-with-video
