### ISSUE TITLE
lozad assumes commas in background-image urls are different images

### ISSUE THREAD

**Issue by antony** [ApoorvSaxena/lozad.js#238]
## Expected Behavior
A mapbox static map url, for example, looks like this:

```
https://api.mapbox.com/styles/v1/mapbox/outdoors-v11/static/-73.7638,42.6564,13,0/600x300@2x?access_token=YOUR-API-KEY-HERE&attribution=false&logo=false
```
I would expect that url to be loaded as a background image, as it is a valid URL.

## Current Behavior
Currently, the url is split into multiple segments on `,` and turned into multiple url()s by lozad

## Possible Solution
A difficult one, since it is probably a breaking change. You could be clever with encoding URLs, and replace all commas which *arent* %2C only, but it's not ideal.

Option B is that you could change the split character to a non-url character, but this too could be challenging.

## Steps to Reproduce (for bugs)
Add a mapbox URL or any URL with commas as a `data-background-src`

## Context
It means I can't use lozad on my site (I can half use it, but I'd rather an all-encompassing solution)

## Tested on:
* Browser Name and version: Chrome Version 81.0.4044.138 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Desktop

**Comment by alex-bowers** [comment]
I'm having the same issue with Cloudinary links. This is an example from their company home page.

```
https://cloudinary-res.cloudinary.com/image/upload/dpr_1,f_auto,q_auto,w_960/b_rgb:eeeeee/v1589377362/website/home-redesign/cloudinary_web_homepage_hero_image.png
```

**Comment by alex-bowers** [comment]
@antony Have you got any thoughts on https://github.com/ApoorvSaxena/lozad.js/pull/239? It's something I need to use. Hope it's useful for you.

**Comment by ApoorvSaxena** [comment]
@alex-bowers thanks for your contribution, fix is merged in master 👍 💯

**Comment by antony** [comment]
@alex-bowers I'm a bit late to the party, but I would have agreed! Glad to see this in master :)
