### ISSUE TITLE
Safari polyfill bug causing lozad to load images outside the viewport

### ISSUE THREAD

**Issue by bsteephenson** [ApoorvSaxena/lozad.js#242]
Ran into a fun bug affecting Safari 11.1.1 and Safari on my iOS 11.4.1 phone. Lozad would load all images on page load, even images that are not in the viewport. I demonstrated this by logging the links that lozad was loading.

The root cause is described in https://github.com/w3c/IntersectionObserver/issues/257 . It's because the root box that the polyfill creates is too big. The fix is to either set the html div's height to 100% or to set doctype <!DOCTYPE html> .

I spent like five hours chasing down this bug. You should maybe add it to the FAQ.

**Comment by ApoorvSaxena** [comment]
@bsteephenson thanks for sharing this information, [FAQs](https://github.com/ApoorvSaxena/lozad.js/wiki/Frequently-Asked-Questions) updated.
