### ISSUE TITLE
Is this project willing take pull request of typescript definitions?

### ISSUE THREAD

**Issue by plantain-00** [ApoorvSaxena/lozad.js#26]
It will be useful for typescript users and improve the experiences on some editors like vscode.

basicly a `index.d.ts` file with:

```ts
type Option = {
    rootMargin?: string;
    threshold?: number;
    load?(element: HTMLElement | HTMLCanvasElement): void;
}

type Observer = {
    observe(): void;
}

declare function lozad(selector?: string, options?: Option): Observer;

declare namespace lozad {
    const prototype: {
    };
}

export as namespace lozad;

export = lozad;
```

**Comment by thiamsantos** [comment]
I think that's a good a ideia @plantain-00

**Comment by ApoorvSaxena** [comment]
@plantain-00 can you share why it will be useful for typescript users? Also, currently we are only shipping `dist` folder when downloaded via npm, do you propose whitelisting the src file as well in that case?

**Comment by thiamsantos** [comment]
I don't know for sure, but I think these definitions are only a file in the root of the project. So no need for use typescript in the code of lozad and these definitions are the only to be whitelisted besides the dist folder.

**Comment by styfle** [comment]
This would be 1 additional file (`lozad.d.ts`) and a 1 line modification to `package.json`

```json
{
  "types": "./lib/lozad.d.ts"
}
```

Think of it like a `.h` file that includes headers and the `.c` file includes the body if you've used C/C++.

**Comment by plantain-00** [comment]
@ApoorvSaxena 
The file describes the types of API of this library.
Typescript needs this for type checking.
For example, the `threshold` is declared as `optional number`, if users set it a `string`, the Typescript will show the error.

There is the link about publishing the types: https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/declaration%20files/Publishing.md
The file can be `./index.d.ts`, or in any directory with `"type": "the path to the file"` in `package.json`.

**Comment by ApoorvSaxena** [comment]
@plantain-00 not able to understand any specific reason to make use of TypeScript over Vanilla JS. Also, this requirement doesn't curtail typescript users to still be able to use `Lozad.js` in their projects.

Foreseeing, that such a case may arise in the future seeking permission to have Coffeescript or any other JS flavour, it'd be better to have this as is.

**Comment by thiamsantos** [comment]
> @plantain-00 not able to understand any specific reason to make use of TypeScript over Vanilla JS. 

You will continue to use vanilla js as before, just the type definitions will be added, wihtout changing the present source code. Lozad will not use typescript.

**Comment by ApoorvSaxena** [comment]
@thiamsantos will need to maintain two codebases then, and similarly for requests for any other JS flavour

**Comment by thiamsantos** [comment]
@thiamsantos will need to maintain two codebases then, and similarly for requests for any other JS flavour

Actually no, the typescript definitions are not a codebase just the definitions for the types of the arguments.

**Comment by thiamsantos** [comment]
Never mind. @plantain-00 added the type definitions to DefinitelyTyped/DefinitelyTyped#19712. So that discussion is useless :smile:
