### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by tzikas97** [ApoorvSaxena/lozad.js#27]
There is a **404 error** with the polyfill file:
[https://rawgithub.com/w3c/IntersectionObserver/gh-pages/polyfill/intersection-observer.js](https://rawgithub.com/w3c/IntersectionObserver/gh-pages/polyfill/intersection-observer.js)

It seems that the file has been removed on branch "gh-pages" over at:
[https://github.com/w3c/IntersectionObserver/tree/gh-pages/polyfill](https://github.com/w3c/IntersectionObserver/tree/gh-pages/polyfill)

**Comment by ApoorvSaxena** [comment]
@tzikas97 thanks for reporting, have fixed temporarily with the new path https://raw.githubusercontent.com/w3c/IntersectionObserver/master/polyfill/intersection-observer.js

Will be adding this as a dependency via `npm` module, so that such situation doesn't arise again.
