### ISSUE TITLE
Srcset

### ISSUE THREAD

**Issue by weaverhe** [ApoorvSaxena/lozad.js#28]
Does your plugin work with srcset? Or only with src?

**Comment by ApoorvSaxena** [comment]
@weaverhe you can define a custom load function while initializing Lozad to make use of srcset instead of `src` for now.

```html
<picture>
  <img class="lozad" data-srcset="medium.jpg 1000w, large.jpg 2000w">
</picture>
```

```js
lozad('.lozad', {
    load: function(el) {
        el.srcset = el.dataset.srcset;
    }
});
```

We'll support `srcset` by default in the library, queued in our tasklist. Thanks.

**Comment by ApoorvSaxena** [comment]
Lozad.js now supports responsive images by default 🍾
