### ISSUE TITLE
Polyfill IntersectionObserver

### ISSUE THREAD

**Issue by aganglada** [ApoorvSaxena/lozad.js#29]
IntersectionObserver is not supported entirely for all the browsers, see here

<img width="1264" alt="screen shot 2017-09-14 at 09 13 35" src="https://user-images.githubusercontent.com/922348/30419083-0b56d578-992d-11e7-9920-45645086f0f9.png">

Make sure we polyfill it optionally, so anyone that wants to support those browsers, can apply this library.

Let's use the official one: https://github.com/w3c/IntersectionObserver/tree/master/polyfill

**Comment by ApoorvSaxena** [comment]
@aganglada [README](https://github.com/ApoorvSaxena/lozad.js#browser-support) clearly mentions the browser support along with reference to polyfill.

**Comment by ApoorvSaxena** [comment]
Have added this question in [FAQs](https://github.com/ApoorvSaxena/lozad.js/wiki/Frequently-Asked-Questions) as well.
