### ISSUE TITLE
Why selectorClass?

### ISSUE THREAD

**Issue by styfle** [ApoorvSaxena/lozad.js#3]
It seems like `selectorClass` is too specific.

It would be better to use `selector` so one could do the following:

```js
new Lozad({
  selector: 'img',
  threshold: 0.1
})
```

Or the following:

```js
new Lozad({
  selector: '#jumbo',
  threshold: 0.1
})
```

Of course you could still select by class, just add a dot.

```js
new Lozad({
  selector: '.lozad',
  threshold: 0.1
})
```

**Comment by ApoorvSaxena** [comment]
Agree, good idea. Will implement the same.

**Comment by ApoorvSaxena** [comment]
it should internally make use of [document.querySelectorAll](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll)

**Comment by ApoorvSaxena** [comment]
@styfle have opened PR https://github.com/ApoorvSaxena/lozad.js/pull/5

**Comment by styfle** [comment]
Thanks!
