### ISSUE TITLE
provide a polyfill

### ISSUE THREAD

**Issue by stephenkingsley** [ApoorvSaxena/lozad.js#34]
IntersectionObserver is high version api [https://caniuse.com/#search=IntersectionObserver](https://caniuse.com/#search=IntersectionObserver). I think we can provide a polyfill version. what do you think?

**Comment by styfle** [comment]
The wiki recommends a polyfill:

https://github.com/ApoorvSaxena/lozad.js/wiki/Frequently-Asked-Questions#how-to-support-browsers-in-which-intersectionobserver-is-not-supported

**Comment by stephenkingsley** [comment]
nice! that is my fault! thx @styfle
