### ISSUE TITLE
Automate publish to npm and bower using travis

### ISSUE THREAD

**Issue by thiamsantos** [ApoorvSaxena/lozad.js#38]
Travis has an [API to publish to npm](https://docs.travis-ci.com/user/deployment/npm/). A bower publish could be triggered when travis finishes to publish to npm using the [bower cli api](https://bower.io/docs/api/). After that done may be easy to remove the dist from the repository (ref #18).

**Comment by zabawaba99** [comment]
I wouldn't mind taking this on. How do you want to publication to happen? Do you want Travis to publish when you create a tag or deploy to a specific branch?

**Comment by ApoorvSaxena** [comment]
creating a tag will suit best
