### ISSUE TITLE
Not working in Edge

### ISSUE THREAD

**Issue by drebus** [ApoorvSaxena/lozad.js#40]
Demo not working in latest Edge. No errors in console.

**Comment by ApoorvSaxena** [comment]
@drebus can you open this [link](https://rawgit.com/w3c/IntersectionObserver/master/polyfill/intersection-observer-test.html) and share the status of tests run in Edge? Also, please share the exact version of Edge

**Comment by drebus** [comment]
@ApoorvSaxena sure, I'm posting screenshot of failed items of test.

![bez tytulu](https://user-images.githubusercontent.com/11090105/30901158-ff1fc438-a366-11e7-91a8-6dbe0bf218df.png)

**Microsoft Edge 40.15063.0.0
Microsoft EdgeHTML 15.15063**

**Comment by kleinfreund** [comment]
I can confirm this. I don’t understand how Edge claims full support, when it clearly doesn’t have it.

![edge](https://user-images.githubusercontent.com/5774638/30955870-7f0c1f06-a435-11e7-86a4-207bdcb897bd.png)
