### ISSUE TITLE
Preloader

### ISSUE THREAD

**Issue by rgfx** [ApoorvSaxena/lozad.js#41]
Would like to make a preloader
Believe that users should have a indication of a loading element.
Is there an .is-loading class or something. 

How can achieve this, thanks?

**Comment by ApoorvSaxena** [comment]
@rgfx there are two approaches to solve this:
- in case your preloader is a gif, you can use it as the default source of element
```html
<img class="lozad" src="loader.gif" data-src="image.png" />
```
- in case you want to use a CSS loader, you can use this selector `.lozad:not([data-loaded])` to select the images which are yet to be lazy loaded
