### ISSUE TITLE
Expose a function to load specific images before they appear

### ISSUE THREAD

**Issue by akxcv** [ApoorvSaxena/lozad.js#42]
It would be useful to be able to preload certain images in advance when certain events are triggered (say, a menu is opened). Currently, though, the `load` function is not exported from the module. It would be useful to reuse it instead of having to write it by yourself.

The only issue I see is that the `load` function is configurable. Although I suppose, we could assign it to the `lozad` object.

Example:
```js
import lozad from 'lozad'

const observer = lozad()
observer.observe()
document.addEventListener('menu:open', () => {
  observer.load('img.language-icon')
})
```

Though `observer.load` doesn't sound right.

**Comment by thiamsantos** [comment]
That's a good feature @akxcv! What do you think @ApoorvSaxena?

**Comment by ApoorvSaxena** [comment]
@akxcv @thiamsantos use case looks perfectly valid. How about using `preload` or `triggerLoad` as function name?

**Comment by thiamsantos** [comment]
`triggerLoad` seems perfect

**Comment by thiamsantos** [comment]
`triggerLoad` seems perfect

**Comment by akxcv** [comment]
Yeah, `triggerLoad` seems fitting!

**Comment by thiamsantos** [comment]
I just opened a pull request adding this feature

**Comment by ApoorvSaxena** [comment]
thanks for getting this done all the way @thiamsantos
