### ISSUE TITLE
IE9 not working - loader Issue

### ISSUE THREAD

**Issue by sepplbmx** [ApoorvSaxena/lozad.js#47]
When emulating IE9, images do not load because of the following error:

The "loaded" property of an undefined or null reference can not be retrieved.

Seems like it hase something to do with the loaded statement. I tried to fix it but I failed:

t.dataset.loaded=!0

Any help would be appreciated.

Thanks,

Sebastian

P.S. Adding the Polyfill does not work either. As far as I understand, Polyfill only helps for IE Versions Prior 9.

**Comment by aderaaij** [comment]
This library uses arrow functions and spread operates, I don't think they're supported in ie9.

**Comment by thiamsantos** [comment]
> This library uses arrow functions and spread operates, I don't think they're supported in ie9.

All these things are transpiled using [babel](https://github.com/babel/babel). So you don't need to worry about these.

**Comment by thiamsantos** [comment]
> The "loaded" property of an undefined or null reference can not be retrieved.

@sepplbmx Actually it happens because [IE9 doesn't support `HTMLElement.dataset`](http://caniuse.com/#feat=dataset).

```js
// so instead of doing this
element.dataset.loaded = true

// a possible fix wuold be do that
element.setAttribute('data-loaded', true)
````

@ApoorvSaxena what do you think about that?

**Comment by aderaaij** [comment]
@thiamsantos Ah sorry, it was late!  Of course it gets transpiled, although the problem is pretty close though. I guess in that case `dataset` should be replaced in the `defaultconfig` as well?

**Comment by ApoorvSaxena** [comment]
> what do you think about that?

@thiamsantos sure, support for [setAttribute](http://caniuse.com/#feat=dom-manip-convenience) is available IE6+

**Comment by lionralfs** [comment]
I've submitted a PR (https://github.com/ApoorvSaxena/lozad.js/pull/54)

**Comment by ApoorvSaxena** [comment]
thanks a ton @lionralfs for the fix 👍 and for testing it in IE9 as well 😃
