### ISSUE TITLE
Check if image is loaded?

### ISSUE THREAD

**Issue by aderaaij** [ApoorvSaxena/lozad.js#49]
It seems that in a gallery with a large numbers of items it can happen that `data-loaded=true` or any class you add in the callback, for that matters, can be applied to an image while the background image is not yet fully loaded. This results in a suddenly appearing image (especially when the images itself are fairly large) because the transition was already applied before the image was loaded in the browser.

I would propose to test if the image is actually loaded before adding the `data-loaded=true` attribute. Maybe like

```
const imgLoad = new Image();
imgLoad.onload = () => {
  element.dataset.loaded = true;
}
imgLoad.src = element.dataset.src;
```
There might be better ways to check if the images are loaded, but you catch my drift :)

edit: This does lead to the loading of two files when the `srcset` file which is loaded is different from the `src` file. This could be fixed by polling if `element.currentSrc` is set and use that image for the `imgLoad.src`.

**Comment by midzer** [comment]
Yeah, incase you want some animation or something like that to kick in, you have to ensure images are properly loaded first of all.

**Comment by stephenkingsley** [comment]
we can provide a list to save imgs loading status.
```
imgsStatus = [{ node: imgObject, status: true }];
```
And when have a img change status, we should update this list, and provide callback function. The developer can do whatever they want in this callback function.

If just add `data-loaded=true` attribute is not helpful and convenient to developers.

**Comment by jimblue** [comment]
Any update about this issue?

**Comment by midzer** [comment]
In my similar library, i simply put `element.classList.add('loaded');` to each element that has been successfully loaded and begin an animation or something if necessary. Works for `video` and components lazy-loading any JavaScript, too.

You can check out code here https://github.com/midzer/lazyobs/blob/master/lazyobs.js

**Comment by jimblue** [comment]
Hi @midzer, Lozad already provide such feature as it `data-loaded` is added on element load.
I'm actually using css to fade in on load like this:

```
.lozad {
  opacity: 0;
  transition: opacity $transition-normal $easeInOut $transition-fast;

  &[data-loaded] {
    opacity: 1;
  }
}
```

It's kind of working 50% of the time as sometime the loaded content popup without fading.

Because is not 100% reliable I was wondering it's because the actual loaded callback is not precise.

I guess this is the subject of this topic...

**Comment by aderaaij** [comment]
@jimblue is right. The data-loaded just happens when the strings get switched from data-src to src, that is not checking if the image is loaded.
Anyway, @jimblue, I made a fork of this repo which has a checking if images are loaded, but I changed some other stuff too. Let me see if I can get a pull request going. You can also add the code I added in the opening of this topic!

**Comment by jimblue** [comment]
@aderaaij cool, sharp code indeed, I didn't understand the meaning at first sight!!!

But honestly, I prefer not customise the code on my side for obvious update reason.

I think I'm gonna wait for your pull request ! (sorry to be lazy... 😄 )

**Comment by jimblue** [comment]
Hi there! Any update about a fix?

**Comment by jimblue** [comment]
Hi @ApoorvSaxena,

This issue start to get old now but it's still unresolved. (more than 4 months)
However it's kind of a high priority one as you tagged it.

There is already a PR on the go here #79 , just need your input on it...
Could you please have a look?

Thank you

Cheers

**Comment by jimblue** [comment]
Hi @ApoorvSaxena !

Any update about this issue? Do you plan to fix it or not?

Cheers

**Comment by justinasdmt** [comment]
Hey guys,
Any update on this? Does anyone have a solution to really check if the image is fully loaded?

**Comment by forepointmc** [comment]
Just have to say that I don't recommend this library to anyone. It sucks ass. I used it on two projects after reading the CSS Tricks article about it, and I've had nothing but issues with it. It doesn't check to see if an image has loaded, data-loaded=true is always present on the element. Images sometimes never load, or half load. The fact that this core issue is still unresolved after so long says it all.

**Comment by jimblue** [comment]
@forepointmc totally agree, worst open source project ever for the number of stars...

**Comment by UisgeBeatha436** [comment]
Any suggestions as an alternative for loading images and iframes?

**Comment by forepointmc** [comment]
Angular 7 uses observers in rxjs and its pretty solid. I think frameworks are the best solution right now

**Comment by jimblue** [comment]
https://github.com/malchata/yall.js

**Comment by jimblue** [comment]
https://github.com/verlok/lazyload

**Comment by jimblue** [comment]
https://github.com/aFarkas/lazysizes

**Comment by jimblue** [comment]
many options !

**Comment by owaisahmed5300** [comment]
Here is example,

var container = document.querySelectorAll('.lozad-container img');
var observer = lozad(container, {
     loaded: function(el) {
         $(el).on('load', function () {
           // When the image is completely loaded
          // code here.
         });
     },
}); 
observer.observe();
