### ISSUE TITLE
If image are after lozad init, image are not loaded

### ISSUE THREAD

**Issue by ethyde** [ApoorvSaxena/lozad.js#50]
Hi,

This library is really impressive, but I just realized that if an image is placed after initialization, it is never loaded.

I have made a little jsbin : https://jsbin.com/bofurugene/2/edit?html,output
And the 100*200 pic never load

So, how to do ?

Thanks.

**Comment by thiamsantos** [comment]
That is an expected behaviour, it will track only the existing images. If you add dynamically another image you can trigger the observer again as described in the Readme.

In your example you could but the initialization of lozad inside an event of hte DOM:

```js
window.addEventListener('load', function() {
  var observer = lozad()
  observer.observe()
})
```

Or just put the script before the closing body:
```html
<img data-src="http://lorempixel.com/100/200/people/" class="lozad" />
<script>
  var observer = lozad()
  observer.observe()
</script>
</body>
```

**Comment by ethyde** [comment]
Thanks for your quick answer @thiamsantos !

I understand for the image added dynamically, but in my case, image exists in the DOM.

I think it would be a good idea to add this case to the documentation because it is not obvious that an existing image that is after initialization should be seen as a dynamically added image. Or that the position of the initialization in the page is of great importance.

**Comment by kleinfreund** [comment]
If it’s not important that lazy-loaded images start being loaded as soon as the relevant part of the DOM is processed, then all parts of the library should be called from within a `DOMContentLoaded` event listener to make sure all of the DOM is parsed.

In general, I don’t see a usecase for calling `observer.observe()` from code that is executed before the DOM is loaded completely.

**Comment by ApoorvSaxena** [comment]
@kleinfreund it will be better if the library user calls `observer.observe()` from within a `DOMContentLoaded` event listener to take care of such cases

**Comment by ownergroup** [comment]
> That is an expected behaviour, it will track only the existing images. If you add dynamically another image you can trigger the observer again as described in the Readme.
> 
> In your example you could do the initialization of lozad inside an event of load:
> 
> ```js
> window.addEventListener('load', function() {
>   var observer = lozad()
>   observer.observe()
> })
> ```
> 
> Or just put the script before the closing body:
> 
> ```
> <img data-src="http://lorempixel.com/100/200/people/" class="lozad" />
> <script>
>   var observer = lozad()
>   observer.observe()
> </script>
> </body>
> ```

Thank you @thiamsantos!! Hours debugging..
