### ISSUE TITLE
Kebab-case classes are not fired

### ISSUE THREAD

**Issue by cnotv** [ApoorvSaxena/lozad.js#53]
Following the documentation, to pick a typical CSS kebab-case class, does not make the plugin fire.

E.g.:
```
const observer = lozad('.is-lazy')
```

**Comment by ApoorvSaxena** [comment]
@cnotv this works as expected, please check this Codepen [demo](https://codepen.io/ApoorvSaxena/pen/VMdexy) also, we have a working [test case](https://github.com/ApoorvSaxena/lozad.js/blob/068b3950649b504c51b9cbf236bf2b03271efe09/test/index.js#L72) for the same as well.
