### ISSUE TITLE
Support videos and components

### ISSUE THREAD

**Issue by midzer** [ApoorvSaxena/lozad.js#56]
Hi all,
i worked on a similar library few weeks ago. Besides `<img>` elements, i got `<video>` and components which need own (heavy) JS to lazy load as well: https://github.com/midzer/lazyobs

Maybe we can merge some ideas into this project :) 

Cheers
midzer

**Comment by ApoorvSaxena** [comment]
@midzer Lozad.js allows lazy loading of iframes, videos, images and other elements (using custom load function). Any specific feature that you want to discuss?

**Comment by midzer** [comment]
@ApoorvSaxena i didn't realize from README video and lazy loading scripts for components is working already. Maybe i find another way to contribute to this cool project :+1:
