### ISSUE TITLE
After update to 1.0.7, data-background-image is no longer working

### ISSUE THREAD

**Issue by lonepalmus** [ApoorvSaxena/lozad.js#57]
I can see it was changed in https://github.com/ApoorvSaxena/lozad.js/commit/068b3950649b504c51b9cbf236bf2b03271efe09 from element.dataset.backgroundImage to element.getAttribute('data-backgroundImage')

But guess it should be element.getAttribute('data-background-image') instead?

**Comment by midzer** [comment]
Yep, according to current README it is
```
<!-- background image example -->
<div class="lozad" data-background-image="image.png">
</div>
```
Either adapt README from code or vice versa.

**Comment by ApoorvSaxena** [comment]
@lonepalmus this will be fixed to have the same behaviour as it has been so far.

**Comment by ApoorvSaxena** [comment]
@lonepalmus this has been fixed, and relevant test cases have been added
