### ISSUE TITLE
Change method signature

### ISSUE THREAD

**Issue by thiamsantos** [ApoorvSaxena/lozad.js#6]
What do you think about changing the method signature from this:
```js
const lozad = new Lozad({
    selectorClass: 'lozad', // for identification of images to lazy load
    rootMargin: '10px 0px', // syntax similar to that of CSS Margin
    threshold: 0.1 // ratio of image convergence
})
lozad.load = function(el) {
	console.log('loading element');
}
```
For something like this:
```js
lozad('.some-selector', {
  rootMargin: '10px 0px',
  threshold: 0.1,
  onLoad() {
    console.log('loading element')
  }
})
```

In that way we would follow some good patterns followed by big libraries out there like [moment](https://momentjs.com/). Additionally [eslint](https://eslint.org/) has a rule that [discourages the use of `new` for side effects](https://eslint.org/docs/rules/no-new). There a [whole talk about that, I think that would be good if you check it out](https://www.youtube.com/watch?v=RdKT70ktaeo).

Best regards.

**Comment by styfle** [comment]
Good points! I agree, the second API looks much better.

**Comment by ApoorvSaxena** [comment]
I hadn't documented this feature, though lozad allows lazy loading elements that are dynamically added to the DOM:
```js
let lozad = new Lozad();
// after new elements are added to the DOM
lozad.activate(); // adds new observer to all the elements present at the time of call of this event
```
what do you suggest for having this functionality in the recommended API interface?

**Comment by thiamsantos** [comment]
I think the best thing to do is recall the function, keep all the things simple. Something like:

```js
const lazyLoad = () => lozad('.some-selector', {
  rootMargin: '10px 0px',
  threshold: 0.1,
  onLoad() {
    console.log('loading element')
  }
})
// initial call
lazyLoad()

// after new elements are added to the DOM
lazyLoad()
```

**Note**: I personally don't like to use the [`new` operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new) because I think it add too much overhead to things that could be much simpler. But if it must be used, the constructor should only receive the paremeters and instantiate the object. All the additional behaviour should be called in others methods. Example:

```js
const lozad = new Lozad('.lozad', {
  rootMargin: '10px 0px', // syntax similar to that of CSS Margin
  threshold: 0.1 // ratio of image convergence
})

lozad.onLoad = function(el) {
  console.log('loading element')
}

// only here the module starts to observes the changes in DOM
lozad.init()
```

I don't know if I made me clear enough, but that's what I think. What are your thoughts about that?

**Comment by ApoorvSaxena** [comment]
@thiamsantos: first approach looks good. 
`onLoad` seems like a post callback which gets triggered after the element loads, though our `load` function documentation is to allow developer to overwrite the implementationof Lozad's original load function with a custom one.

**Comment by thiamsantos** [comment]
> @thiamsantos: first approach looks good.

Cool! So I will a pull request.

> onLoad seems like a post callback which gets triggered after the element loads, though our load function documentation is to allow developer to overwrite the implementation of Lozad's original load function with a custom one.

Do you have any suggestions for a better name? I think that `load` is a little bit weird too. What about something similar to the [lifycycle events](https://facebook.github.io/react/docs/react-component.html#the-component-lifecycle) from [React](https://facebook.github.io/react/), like `willAppear` or `willLoad`, what do you think about that?

**Comment by ApoorvSaxena** [comment]
how about `defineLoad`?

**Comment by thiamsantos** [comment]
`customLoad` seems good to me. I still prefer a name that remember a event based callback like `willAppear`, but it is totally my taste. It will `customLoad` then?

**Comment by thiamsantos** [comment]
Reading the code I realize that you were right since the beginning `load` is the best name for the function.

**Comment by ApoorvSaxena** [comment]
@thiamsantos there's a catch in the above implementation though, that a new object will instantiate a new IntersectionObserver instead of utilising already available observer instance.

**Comment by thiamsantos** [comment]
> @thiamsantos there's a catch in the above implementation though, that a new object will instantiate a new IntersectionObserver instead of utilising already available observer instance.

Yeah, but I think that's not a big issue. In my opionion, a better interface or design of the code is more desirable than a faster code. In other words, I don't believe that kind of optimization bring so much benefit that worth the use of it.

**Comment by ApoorvSaxena** [comment]
@thiamsantos performance is the essence of this library, this will be a common use case in dynamically added elements which is a common use case when using frameworks or ajax based approach.
I'll be happy to merge if you make these changes.

**Comment by thiamsantos** [comment]
> @thiamsantos performance is the essence of this library, this will be a common use case in dynamically added elements which is a common use case when using frameworks or ajax based approach.

I will update my pull request.

**Comment by thiamsantos** [comment]
> I will update my pull request.

Done. Now I use [factory functions](https://medium.com/javascript-scene/javascript-factory-functions-with-es6-4d224591a8b1):

```js
const observer = lozad() // cache the intersection observer instance
observer.observe() // initiate intersection observe

// Dynamic load elements
observer.observe() // observe newly added elements
```

@ApoorvSaxena what do you think?

**Comment by ApoorvSaxena** [comment]
https://github.com/ApoorvSaxena/lozad.js/pull/9 was merged
