### ISSUE TITLE
deprecating Bower support

### ISSUE THREAD

**Issue by ApoorvSaxena** [ApoorvSaxena/lozad.js#70]
Considering that:
- Bower itself has been recommending use of Yarn for package installation
- No way to automate publishing update to bower
- most of the users are using jsDeliver CDN with ~1M downloads/month or npm package

thanks to @thiamsantos for suggesting this before as well, with data it's evident now that folks are using CDN directly or Yarn installation only.

**Comment by ecollis6** [comment]
I can help with this. Do we just need to update the bower.json description to instruct users to install via npm/yarn?

**Comment by thiamsantos** [comment]
The steps are:

1. Before, notify all users of your module who might be affected by this change (see below)
2. Remove all distribution files and bower.json from repository
3. Tag repository with new major semver version (e.g from 3.5.6 to 4.0.0)
4. Don’t remove your component from Bower registry (via bower unregister)

More information can be found here: [How to drop Bower support?](https://bower.io/blog/2017/how-to-drop-bower-support/)

**Comment by ApoorvSaxena** [comment]
turns out bower tracks version update via git tag associated with library repo, need to reconsider this decision now :(

[![Bower version](https://badge.fury.io/bo/lozad.svg)](https://badge.fury.io/bo/lozad)

**Comment by thiamsantos** [comment]
> turns out bower tracks version update via git tag associated with library repo, need to reconsider this decision now :(

That's why is recommend tag with a new major version. So any bower users will continue to use the library as usual. But they will not be able to update the library.

**Comment by ApoorvSaxena** [comment]
@thiamsantos what I meant is that, supporting Bower doesn't need any extra setup and can be continued as it's working currently.

**Comment by thiamsantos** [comment]
> @thiamsantos what I meant is that, supporting Bower doesn't need any extra setup and can be continued as it's working currently.

Yes, but we still need to bump the version of `bower.json` to match the tags. And if bower support was dropped, will be possible to remove the dist folder to cleanup the git diffs and the repo.

Basically anyone use bower, I just can't see a good reason to continue to support it.

**Comment by ApoorvSaxena** [comment]
closing this issue for now
