### ISSUE TITLE
Threshold not working

### ISSUE THREAD

**Issue by jimblue** [ApoorvSaxena/lozad.js#72]
Hi,

I was reading the official documentation to understand how Intersection observer work:

https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API#Intersection_observer_options

But while making some tests to fine tune, I've notice that changing threshold to any value doesn't delay the callback at all.

For exemple, the callback should wait until all pixel are in view if the threshold is set to 1 but that's not the case.

Am I the only one with this problem?

Cheers

**Comment by jimblue** [comment]
@ApoorvSaxena can you confirm this bug?

**Comment by ApoorvSaxena** [comment]
@jimblue can you share a codepen sample for failing case?

**Comment by jimblue** [comment]
@ApoorvSaxena nothing special, even with the most basic setup, threshold doesn't work as expected.

In the following **pen** exemple the threshold is set to 1.
The callback should wait until all pixel are in view but that's not the case.

https://codepen.io/jimblue/pen/jaVNjP

**Comment by jimblue** [comment]
@ApoorvSaxena can you confirm this bug?

**Comment by ApoorvSaxena** [comment]
@jimblue this is surely not a bug, instead if you look closely, your image elements don't have a default size when the image is not loaded, and thus are completely visible in the viewport, after they load via lozad, you are able to see them placed out of the viewport.

See this codepen for reference https://codepen.io/ApoorvSaxena/pen/oGgxJr

**Comment by jimblue** [comment]
@ApoorvSaxena, to be sure I've took you pen to test threshold this time and it's still not working as it suppose to...

You should have a look to the definition of threshold from mozilla.org:

> **threshold**
Either a single number or an array of numbers which indicate at what percentage of the target's visibility the observer's callback should be executed. If you only want to detect when visibility passes the 50% mark, you can use a value of 0.5. If you want the callback run every time visibility passes another 25%, you would specify the array [0, 0.25, 0.5, 0.75, 1]. The default is 0 (meaning as soon as even one pixel is visible, the callback will be run). A value of 1.0 means that the threshold isn't considered passed until every pixel is visible.

In your pen I've only modified the threshold that is now set to 1.
In this new pen the callback should wait until all pixel are in view but that's still not the case. You can check by yourself.

https://codepen.io/jimblue/pen/jaVNjP

Do you confirm?

**Comment by ApoorvSaxena** [comment]
@jimblue again in the above codepen you have set threshold on the img element which has no height initially, and gets rendered asap. You can check out the correct implementation in this [example](https://codepen.io/ApoorvSaxena/full/vWmyQg/)

**Comment by jimblue** [comment]
@ApoorvSaxena thank you so much for the explanation. 😄 
Indeed with default image size provide it's working well:

https://codepen.io/jimblue/pen/jamzdN
