### ISSUE TITLE
How to use placeholder images

### ISSUE THREAD

**Issue by marko-mlinarevic** [ApoorvSaxena/lozad.js#73]
One fast question. Do I myself need to implement the logic for placeholder images?

**Comment by Yurgeman** [comment]
regards, is 2 versions:
1. to use into src - preloader `src="tpl/img/spinner.gif"`
```<img class="lozad" src="tpl/img/spinner.gif" data-src="tpl/images/catalog/catalog-item__01.jpeg">```

2. Use preloader, as background image for parent container
