### ISSUE TITLE
Usage of data-index and issue with images not loading

### ISSUE THREAD

**Issue by czescwojtek** [ApoorvSaxena/lozad.js#74]
Hi there, 

I'd like you to clarify the usage of data-index attribute if possible. You don't mention it anywhere in readme nor is it included in code but you use it in demo page (was there different demo page before?). 
I am facing issue where random images do not render when are visible for first time but scrolling over them again causes a image to finally pop up. Utilising data-index attribute has slightly improved overall experience (don't know why) but it keeps happen occasionally. Do you have any idea what might be causing the issue? I should mention I have couple of small-sized images packed next to each other, let's say 4 images in a 700 x 500 px rectangle.

Cheers,
Wojtek

**Comment by ApoorvSaxena** [comment]
@czescwojtek Please find the comments inline.

> I'd like you to clarify the usage of data-index attribute if possible. You don't mention it anywhere in readme nor is it included in code but you use it in demo page (was there different demo page before?).

It's only for demo purpose and has no significance with the working of library.

> I am facing issue where random images do not render when are visible for first time but scrolling over them again causes a image to finally pop up. 

This is possible if you move super fast over the area (where you are lazy loading your images), in which case intersection observer doesn't fire at all.

To avoid this issue, you can use `rootMargin` during initialisation of Lozad, which adds extra boundary to your images triggering the loading of images as soon as the boundaries are hit. Read more about [rootMargin](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver/rootMargin).
