### ISSUE TITLE
lozad.js with picture-element to use src from source

### ISSUE THREAD

**Issue by skaltenegger** [ApoorvSaxena/lozad.js#77]
Hi there,

First of all great work, much appreciated!

I'm using lozad with the `<picture>` element like the following structure:
```
<picture>
    <!--[if IE 9]><video style="display: none;"><![endif]-->
      <source media="(min-width: 1024px)" data-srcset="...">
      <source media="(min-width: 768px)" data-srcset="...">
      <source data-srcset="...">
    <!--[if IE 9]></video><![endif]-->
    <img class="lozad" data-src="" alt="...">
</picture>
```

It happens that the final rendered image gets the `data-src` of the `<img>`-tag as its `src` rather than the desired source coming from the `srcset` of the matching `<source>`. Did I miss anything in the code above? I initialize it via simply calling `observer.observe();`

Thanks a lot for getting back to me,
Stefan

**Comment by takakii** [comment]
Does the source element also need the a class name 'lozad'?

**Comment by takakii** [comment]
Does the source element also need the class name 'lozad' and `data-src`?

**Comment by dutchenkoOleg** [comment]
just created pull request https://github.com/ApoorvSaxena/lozad.js/pull/80

**Comment by iamdubx** [comment]
Is it implemented? This feature is must have

**Comment by dutchenkoOleg** [comment]
@iamdubx Fixed problems across forks https://github.com/ApoorvSaxena/lozad.js/pull/80.
waiting for approve

**Comment by ApoorvSaxena** [comment]
thanks to @dutchenkoOleg for getting the issue related to IE fixed.
