### ISSUE TITLE
Feature request: Low Quality Image Placeholders (LQIP)

### ISSUE THREAD

**Issue by lsarni** [ApoorvSaxena/lozad.js#87]
Would it be possible to keep the current behavior but once the image appears on the screen first load a lower quality image and then the final image?
This would reduce the time in which the image isn't display once the user reaches it.

**Comment by ApoorvSaxena** [comment]
@lsarni you can load the LQIP as inline image by default, and add the original source of image in `data-src` attribute of image. This will allow you to load LQIP by default when the page loads, and once the image gets inside visible area original image can be loaded

**Comment by lsarni** [comment]
@ApoorvSaxena right, I could use low quality image as a placeholder but that would mean I still load data that the user might never see which is what I want to avoid.
By loading a low quality image once the user reaches the image then it will take less time to display something and I won't be loading unnecessary data.
