### ISSUE TITLE
Images are being observed by lozad, but not lazily loaded on scrolling.

### ISSUE THREAD

**Issue by abhimrawks** [ApoorvSaxena/lozad.js#96]
_In network calls_: All images are loaded at once instead of getting loaded only when they appear in the viewport.
_In console_: They get printed only when they appear in the viewport. I am able to print on the console using load() function. So the library has access to the images. 

The code is minimal to test the library
```html
<html>
<head>
	<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/lozad/dist/lozad.min.js"></script>
</head>

<body>

        <img class='lozad' style="height: 200px;" src="./img/1.jpg"></br>
	<img class='lozad' style="height: 200px;" src="./img/2.jpg"></br>	
	<img class='lozad' style="height: 200px;" src="./img/3.jpg"></br>
	<img class='lozad' style="height: 200px;" src="./img/4.jpg"></br>
	<img class='lozad' style="height: 200px;" src="./img/5.jpg"></br>

</body>

<script type="text/javascript">
	console.log("entered");
		const observer = lozad('.lozad',
		{
			load: function(){
				console.log('loaded');
			}
		});
	
		observer.observe();
	</script>
</html>
```

Browser: Version 64.0.3282.186 (Official Build) (64-bit)
OS: macOS High Sierra

**Comment by damac23** [comment]
That is because you've already put the images into the src-attribute.
You need to use a placeholder image in src and the real image in data-src.
