### ISSUE TITLE
Backround image URL with special characters fails

### ISSUE THREAD

**Issue by PekkaPLeppanen** [ApoorvSaxena/lozad.js#97]
Here's an [example image](https://cdn.asunnot.oikotie.fi/56pJShdOjYu66RkVvvFT_nmIEk8=/fit-in/980x550/filters:watermark(https://cdn.asunnot.oikotie.fi/FNgYc0cxRts1I9PguvqoW4Bqtrw=/static.asunnot.oikotie.fi/oikotie_watermark.png,0,-1,1):background_color(white):format(jpeg)/ot-real-estate-mediabank-prod/864/859/source/178958468) with special characters in URL. It has parenthesis in the URL.

This URL cannot be used as a lazy loading background image as such, because Lozad does not escape special characters and it has unquoted URI in the `element.style.backgroundImage` attribute.

According to [W3 specs](https://www.w3.org/TR/CSS2/syndata.html#value-def-uri) some special characters has to be escaped:
> Some characters appearing in an unquoted URI, such as parentheses, white space characters, single quotes (') and double quotes ("), must be escaped with a backslash so that the resulting URI value is a URI token: '\(', '\)'.

Easiest solution for this is to add quotes to the URI (src/lozad.js#26):
```
element.style.backgroundImage = `url('${element.getAttribute('data-background-image')}')`
```

**Comment by ApoorvSaxena** [comment]
@PekkaPLeppanen Pull request is welcome

**Comment by ApoorvSaxena** [comment]
[Lozad's npm package](https://www.npmjs.com/package/lozad) has been bumped and published
